
export interface Brawler {
  id: number;
  name: string;
  image: string;
  rarity: 'Common' | 'Rare' | 'Super Rare' | 'Epic' | 'Mythic' | 'Legendary';
}

export const brawlers: Brawler[] = [
  { id: 1, name: 'Shelly', image: 'https://cdn.brawlify.com/brawlers/borderless/16000000.png', rarity: 'Common' },
  { id: 2, name: 'Colt', image: 'https://cdn.brawlify.com/brawlers/borderless/16000001.png', rarity: 'Rare' },
  { id: 3, name: 'Bull', image: 'https://cdn.brawlify.com/brawlers/borderless/16000002.png', rarity: 'Rare' },
  { id: 4, name: 'Brock', image: 'https://cdn.brawlify.com/brawlers/borderless/16000003.png', rarity: 'Rare' },
  { id: 5, name: 'Rico', image: 'https://cdn.brawlify.com/brawlers/borderless/16000004.png', rarity: 'Super Rare' },
  { id: 6, name: 'Spike', image: 'https://cdn.brawlify.com/brawlers/borderless/16000005.png', rarity: 'Legendary' },
  { id: 7, name: 'Barley', image: 'https://cdn.brawlify.com/brawlers/borderless/16000006.png', rarity: 'Rare' },
  { id: 8, name: 'Jessie', image: 'https://cdn.brawlify.com/brawlers/borderless/16000007.png', rarity: 'Super Rare' },
  { id: 9, name: 'Nita', image: 'https://cdn.brawlify.com/brawlers/borderless/16000008.png', rarity: 'Rare' },
  { id: 10, name: 'Dynamike', image: 'https://cdn.brawlify.com/brawlers/borderless/16000009.png', rarity: 'Super Rare' },
  { id: 11, name: 'El-Primo', image: 'https://cdn.brawlify.com/brawlers/borderless/16000010.png', rarity: 'Rare' },
  { id: 12, name: 'Mortis', image: 'https://cdn.brawlify.com/brawlers/borderless/16000011.png', rarity: 'Mythic' },
  { id: 13, name: 'Crow', image: 'https://cdn.brawlify.com/brawlers/borderless/16000012.png', rarity: 'Legendary' },
  { id: 14, name: 'Poco', image: 'https://cdn.brawlify.com/brawlers/borderless/16000013.png', rarity: 'Rare' },
  { id: 15, name: 'Bo', image: 'https://cdn.brawlify.com/brawlers/borderless/16000014.png', rarity: 'Epic' },
  { id: 16, name: 'Piper', image: 'https://cdn.brawlify.com/brawlers/borderless/16000015.png', rarity: 'Epic' },
  { id: 17, name: 'Pam', image: 'https://cdn.brawlify.com/brawlers/borderless/16000016.png', rarity: 'Epic' },
  { id: 18, name: 'Tara', image: 'https://cdn.brawlify.com/brawlers/borderless/16000017.png', rarity: 'Mythic' },
  { id: 19, name: 'Darryl', image: 'https://cdn.brawlify.com/brawlers/borderless/16000018.png', rarity: 'Super Rare' },
  { id: 20, name: 'Penny', image: 'https://cdn.brawlify.com/brawlers/borderless/16000019.png', rarity: 'Super Rare' },
  { id: 21, name: 'Frank', image: 'https://cdn.brawlify.com/brawlers/borderless/16000020.png', rarity: 'Epic' },
  { id: 22, name: 'Gene', image: 'https://cdn.brawlify.com/brawlers/borderless/16000021.png', rarity: 'Mythic' },
  { id: 23, name: 'Tick', image: 'https://cdn.brawlify.com/brawlers/borderless/16000022.png', rarity: 'Super Rare' },
  { id: 24, name: 'Leon', image: 'https://cdn.brawlify.com/brawlers/borderless/16000023.png', rarity: 'Legendary' },
  { id: 25, name: 'Rosa', image: 'https://cdn.brawlify.com/brawlers/borderless/16000024.png', rarity: 'Rare' },
  { id: 26, name: 'Carl', image: 'https://cdn.brawlify.com/brawlers/borderless/16000025.png', rarity: 'Super Rare' },
  { id: 27, name: 'Bibi', image: 'https://cdn.brawlify.com/brawlers/borderless/16000026.png', rarity: 'Epic' },
  { id: 28, name: '8-Bit', image: 'https://cdn.brawlify.com/brawlers/borderless/16000027.png', rarity: 'Super Rare' },
  { id: 29, name: 'Sandy', image: 'https://cdn.brawlify.com/brawlers/borderless/16000028.png', rarity: 'Legendary' },
  { id: 30, name: 'Bea', image: 'https://cdn.brawlify.com/brawlers/borderless/16000029.png', rarity: 'Epic' },
  { id: 31, name: 'Emz', image: 'https://cdn.brawlify.com/brawlers/borderless/16000030.png', rarity: 'Epic' },
  { id: 32, name: 'Mr. P', image: 'https://cdn.brawlify.com/brawlers/borderless/16000031.png', rarity: 'Mythic' },
  { id: 33, name: 'Max', image: 'https://cdn.brawlify.com/brawlers/borderless/16000032.png', rarity: 'Mythic' },
  { id: 34, name: 'Jacky', image: 'https://cdn.brawlify.com/brawlers/borderless/16000034.png', rarity: 'Super Rare' },
  { id: 35, name: 'Gale', image: 'https://cdn.brawlify.com/brawlers/borderless/16000035.png', rarity: 'Epic' },
  { id: 36, name: 'Nani', image: 'https://cdn.brawlify.com/brawlers/borderless/16000036.png', rarity: 'Epic' },
  { id: 37, name: 'Sprout', image: 'https://cdn.brawlify.com/brawlers/borderless/16000037.png', rarity: 'Mythic' },
  { id: 38, name: 'Surge', image: 'https://cdn.brawlify.com/brawlers/borderless/16000038.png', rarity: 'Legendary' },
  { id: 39, name: 'Colette', image: 'https://cdn.brawlify.com/brawlers/borderless/16000039.png', rarity: 'Epic' },
  { id: 40, name: 'Amber', image: 'https://cdn.brawlify.com/brawlers/borderless/16000040.png', rarity: 'Legendary' },
  { id: 41, name: 'Lou', image: 'https://cdn.brawlify.com/brawlers/borderless/16000041.png', rarity: 'Mythic' },
  { id: 42, name: 'Byron', image: 'https://cdn.brawlify.com/brawlers/borderless/16000042.png', rarity: 'Mythic' },
  { id: 43, name: 'Edgar', image: 'https://cdn.brawlify.com/brawlers/borderless/16000043.png', rarity: 'Epic' },
  { id: 44, name: 'Ruffs', image: 'https://cdn.brawlify.com/brawlers/borderless/16000044.png', rarity: 'Mythic' },
  { id: 45, name: 'Stu', image: 'https://cdn.brawlify.com/brawlers/borderless/16000045.png', rarity: 'Epic' },
  { id: 46, name: 'Belle', image: 'https://cdn.brawlify.com/brawlers/borderless/16000046.png', rarity: 'Epic' },
  { id: 47, name: 'Squeak', image: 'https://cdn.brawlify.com/brawlers/borderless/16000047.png', rarity: 'Mythic' },
  { id: 48, name: 'Grom', image: 'https://cdn.brawlify.com/brawlers/borderless/16000048.png', rarity: 'Epic' },
  { id: 49, name: 'Buzz', image: 'https://cdn.brawlify.com/brawlers/borderless/16000049.png', rarity: 'Mythic' },
  { id: 50, name: 'Griff', image: 'https://cdn.brawlify.com/brawlers/borderless/16000050.png', rarity: 'Epic' },
  { id: 51, name: 'Ash', image: 'https://cdn.brawlify.com/brawlers/borderless/16000051.png', rarity: 'Epic' },
  { id: 52, name: 'Meg', image: 'https://cdn.brawlify.com/brawlers/borderless/16000052.png', rarity: 'Legendary' },
  { id: 53, name: 'Lola', image: 'https://cdn.brawlify.com/brawlers/borderless/16000053.png', rarity: 'Epic' },
  { id: 54, name: 'Fang', image: 'https://cdn.brawlify.com/brawlers/borderless/16000054.png', rarity: 'Mythic' },
  { id: 55, name: 'Eve', image: 'https://cdn.brawlify.com/brawlers/borderless/16000056.png', rarity: 'Mythic' },
  { id: 56, name: 'Janet', image: 'https://cdn.brawlify.com/brawlers/borderless/16000057.png', rarity: 'Mythic' },
  { id: 57, name: 'Bonnie', image: 'https://cdn.brawlify.com/brawlers/borderless/16000058.png', rarity: 'Epic' },
  { id: 58, name: 'Otis', image: 'https://cdn.brawlify.com/brawlers/borderless/16000059.png', rarity: 'Mythic' },
  { id: 59, name: 'Sam', image: 'https://cdn.brawlify.com/brawlers/borderless/16000060.png', rarity: 'Epic' },
  { id: 60, name: 'Gus', image: 'https://cdn.brawlify.com/brawlers/borderless/16000061.png', rarity: 'Super Rare' },
  { id: 61, name: 'Buster', image: 'https://cdn.brawlify.com/brawlers/borderless/16000062.png', rarity: 'Mythic' },
  { id: 62, name: 'Chester', image: 'https://cdn.brawlify.com/brawlers/borderless/16000063.png', rarity: 'Legendary' },
  { id: 63, name: 'Gray', image: 'https://cdn.brawlify.com/brawlers/borderless/16000064.png', rarity: 'Mythic' },
  { id: 64, name: 'Mandy', image: 'https://cdn.brawlify.com/brawlers/borderless/16000065.png', rarity: 'Epic' },
  { id: 65, name: 'R-T', image: 'https://cdn.brawlify.com/brawlers/borderless/16000066.png', rarity: 'Mythic' },
  { id: 66, name: 'Willow', image: 'https://cdn.brawlify.com/brawlers/borderless/16000067.png', rarity: 'Mythic' },
  { id: 67, name: 'Maisie', image: 'https://cdn.brawlify.com/brawlers/borderless/16000068.png', rarity: 'Epic' },
  { id: 68, name: 'Hank', image: 'https://cdn.brawlify.com/brawlers/borderless/16000069.png', rarity: 'Epic' },
  { id: 69, name: 'Cordelius', image: 'https://cdn.brawlify.com/brawlers/borderless/16000070.png', rarity: 'Legendary' },
  { id: 70, name: 'Doug', image: 'https://cdn.brawlify.com/brawlers/borderless/16000071.png', rarity: 'Mythic' },
  { id: 71, name: 'Pearl', image: 'https://cdn.brawlify.com/brawlers/borderless/16000072.png', rarity: 'Epic' },
  { id: 72, name: 'Chuck', image: 'https://cdn.brawlify.com/brawlers/borderless/16000073.png', rarity: 'Mythic' },
  { id: 73, name: 'Charlie', image: 'https://cdn.brawlify.com/brawlers/borderless/16000074.png', rarity: 'Mythic' },
  { id: 74, name: 'Mico', image: 'https://cdn.brawlify.com/brawlers/borderless/16000075.png', rarity: 'Mythic' },
  { id: 75, name: 'Kit', image: 'https://cdn.brawlify.com/brawlers/borderless/16000076.png', rarity: 'Legendary' },
  { id: 76, name: 'Larry & Lawrie', image: 'https://cdn.brawlify.com/brawlers/borderless/16000077.png', rarity: 'Epic' },
  { id: 77, name: 'Melodie', image: 'https://cdn.brawlify.com/brawlers/borderless/16000078.png', rarity: 'Mythic' },
  { id: 78, name: 'Angelo', image: 'https://cdn.brawlify.com/brawlers/borderless/16000079.png', rarity: 'Epic' },
  { id: 79, name: 'Draco', image: 'https://cdn.brawlify.com/brawlers/borderless/16000080.png', rarity: 'Legendary' },
  { id: 80, name: 'Lily', image: 'https://cdn.brawlify.com/brawlers/borderless/16000081.png', rarity: 'Mythic' },
  { id: 81, name: 'Berry', image: 'https://cdn.brawlify.com/brawlers/borderless/16000082.png', rarity: 'Epic' },
  { id: 82, name: 'Clancy', image: 'https://cdn.brawlify.com/brawlers/borderless/16000083.png', rarity: 'Mythic' },
  { id: 83, name: 'Moe', image: 'https://cdn.brawlify.com/brawlers/borderless/16000084.png', rarity: 'Mythic' },
  { id: 84, name: 'Kenji', image: 'https://cdn.brawlify.com/brawlers/borderless/16000085.png', rarity: 'Legendary' },
  { id: 85, name: 'Shade', image: 'https://cdn.brawlify.com/brawlers/borderless/16000086.png', rarity: 'Epic' },
  { id: 86, name: 'Juju', image: 'https://cdn.brawlify.com/brawlers/borderless/16000087.png', rarity: 'Mythic' },
  { id: 87, name: 'Meeple', image: 'https://cdn.brawlify.com/brawlers/borderless/16000089.png', rarity: 'Epic' },
  { id: 88, name: 'Ollie', image: 'https://cdn.brawlify.com/brawlers/borderless/16000090.png', rarity: 'Mythic' },
  //{ id: 89, name: 'Lumi', image: 'https://cdn.brawlify.com/brawlers/borderless/16000091.png', rarity: 'Mythic' },
  { id: 90, name: 'Finx', image: 'https://cdn.brawlify.com/brawlers/borderless/16000092.png', rarity: 'Mythic' }
];
