
export interface Brawler {
  id: number;
  name: string;
  image: string;
  rarity: 'Common' | 'Rare' | 'Super Rare' | 'Epic' | 'Mythic' | 'Legendary' | 'Chromatic';
}

export const brawlers: Brawler[] = [
  { id: 1, name: 'Shelly', image: 'https://cdn.brawlify.com/brawlers/borders/16000000.png', rarity: 'Common' },
  { id: 2, name: 'Nita', image: 'https://cdn.brawlify.com/brawlers/borders/16000001.png', rarity: 'Common' },
  { id: 3, name: 'Colt', image: 'https://cdn.brawlify.com/brawlers/borders/16000002.png', rarity: 'Common' },
  { id: 4, name: 'Bull', image: 'https://cdn.brawlify.com/brawlers/borders/16000003.png', rarity: 'Common' },
  { id: 5, name: 'Jessie', image: 'https://cdn.brawlify.com/brawlers/borders/16000004.png', rarity: 'Common' },
  { id: 6, name: 'Brock', image: 'https://cdn.brawlify.com/brawlers/borders/16000005.png', rarity: 'Common' },
  { id: 7, name: 'Dynamike', image: 'https://cdn.brawlify.com/brawlers/borders/16000006.png', rarity: 'Common' },
  { id: 8, name: 'Bo', image: 'https://cdn.brawlify.com/brawlers/borders/16000007.png', rarity: 'Common' },
  { id: 9, name: 'Tick', image: 'https://cdn.brawlify.com/brawlers/borders/16000020.png', rarity: 'Common' },
  { id: 10, name: 'El Primo', image: 'https://cdn.brawlify.com/brawlers/borders/16000008.png', rarity: 'Rare' },
  { id: 11, name: 'Barley', image: 'https://cdn.brawlify.com/brawlers/borders/16000009.png', rarity: 'Rare' },
  { id: 12, name: 'Poco', image: 'https://cdn.brawlify.com/brawlers/borders/16000010.png', rarity: 'Rare' },
  { id: 13, name: 'Rosa', image: 'https://cdn.brawlify.com/brawlers/borders/16000021.png', rarity: 'Rare' },
  { id: 14, name: 'Rico', image: 'https://cdn.brawlify.com/brawlers/borders/16000011.png', rarity: 'Super Rare' },
  { id: 15, name: 'Darryl', image: 'https://cdn.brawlify.com/brawlers/borders/16000014.png', rarity: 'Super Rare' },
  { id: 16, name: 'Penny', image: 'https://cdn.brawlify.com/brawlers/borders/16000015.png', rarity: 'Super Rare' },
  { id: 17, name: 'Carl', image: 'https://cdn.brawlify.com/brawlers/borders/16000019.png', rarity: 'Super Rare' },
  { id: 18, name: 'Jacky', image: 'https://cdn.brawlify.com/brawlers/borders/16000037.png', rarity: 'Super Rare' },
  { id: 19, name: 'Piper', image: 'https://cdn.brawlify.com/brawlers/borders/16000012.png', rarity: 'Epic' },
  { id: 20, name: 'Pam', image: 'https://cdn.brawlify.com/brawlers/borders/16000013.png', rarity: 'Epic' },
  { id: 21, name: 'Frank', image: 'https://cdn.brawlify.com/brawlers/borders/16000016.png', rarity: 'Epic' },
  { id: 22, name: 'Bibi', image: 'https://cdn.brawlify.com/brawlers/borders/16000022.png', rarity: 'Epic' },
  { id: 23, name: 'Bea', image: 'https://cdn.brawlify.com/brawlers/borders/16000030.png', rarity: 'Epic' },
  { id: 24, name: 'Nani', image: 'https://cdn.brawlify.com/brawlers/borders/16000038.png', rarity: 'Epic' },
  { id: 25, name: 'Edgar', image: 'https://cdn.brawlify.com/brawlers/borders/16000045.png', rarity: 'Epic' },
  { id: 26, name: 'Griff', image: 'https://cdn.brawlify.com/brawlers/borders/16000049.png', rarity: 'Epic' },
  { id: 27, name: 'Mortis', image: 'https://cdn.brawlify.com/brawlers/borders/16000017.png', rarity: 'Mythic' },
  { id: 28, name: 'Tara', image: 'https://cdn.brawlify.com/brawlers/borders/16000018.png', rarity: 'Mythic' },
  { id: 29, name: 'Gene', image: 'https://cdn.brawlify.com/brawlers/borders/16000023.png', rarity: 'Mythic' },
  { id: 30, name: 'Max', image: 'https://cdn.brawlify.com/brawlers/borders/16000025.png', rarity: 'Mythic' },
  { id: 31, name: 'Mr. P', image: 'https://cdn.brawlify.com/brawlers/borders/16000026.png', rarity: 'Mythic' },
  { id: 32, name: 'Sprout', image: 'https://cdn.brawlify.com/brawlers/borders/16000031.png', rarity: 'Mythic' },
  { id: 33, name: 'Byron', image: 'https://cdn.brawlify.com/brawlers/borders/16000044.png', rarity: 'Mythic' },
  { id: 34, name: 'Squeak', image: 'https://cdn.brawlify.com/brawlers/borders/16000048.png', rarity: 'Mythic' },
  { id: 35, name: 'Spike', image: 'https://cdn.brawlify.com/brawlers/borders/16000027.png', rarity: 'Legendary' },
  { id: 36, name: 'Crow', image: 'https://cdn.brawlify.com/brawlers/borders/16000028.png', rarity: 'Legendary' },
  { id: 37, name: 'Leon', image: 'https://cdn.brawlify.com/brawlers/borders/16000029.png', rarity: 'Legendary' },
  { id: 38, name: 'Sandy', image: 'https://cdn.brawlify.com/brawlers/borders/16000032.png', rarity: 'Legendary' },
  { id: 39, name: 'Amber', image: 'https://cdn.brawlify.com/brawlers/borders/16000042.png', rarity: 'Legendary' },
  { id: 40, name: 'Meg', image: 'https://cdn.brawlify.com/brawlers/borders/16000050.png', rarity: 'Legendary' },
  { id: 41, name: 'Gale', image: 'https://cdn.brawlify.com/brawlers/borders/16000034.png', rarity: 'Chromatic' },
  { id: 42, name: 'Surge', image: 'https://cdn.brawlify.com/brawlers/borders/16000039.png', rarity: 'Chromatic' },
  { id: 43, name: 'Colette', image: 'https://cdn.brawlify.com/brawlers/borders/16000040.png', rarity: 'Chromatic' },
  { id: 44, name: 'Lou', image: 'https://cdn.brawlify.com/brawlers/borders/16000043.png', rarity: 'Chromatic' },
  { id: 45, name: 'Colonel Ruffs', image: 'https://cdn.brawlify.com/brawlers/borders/16000046.png', rarity: 'Chromatic' },
  { id: 46, name: 'Belle', image: 'https://cdn.brawlify.com/brawlers/borders/16000047.png', rarity: 'Chromatic' },
  { id: 47, name: 'Buzz', image: 'https://cdn.brawlify.com/brawlers/borders/16000051.png', rarity: 'Chromatic' },
  { id: 48, name: 'Ash', image: 'https://cdn.brawlify.com/brawlers/borders/16000052.png', rarity: 'Chromatic' },
  { id: 49, name: 'Lola', image: 'https://cdn.brawlify.com/brawlers/borders/16000053.png', rarity: 'Chromatic' },
  { id: 50, name: 'Fang', image: 'https://cdn.brawlify.com/brawlers/borders/16000054.png', rarity: 'Chromatic' },
  { id: 51, name: 'Eve', image: 'https://cdn.brawlify.com/brawlers/borders/16000056.png', rarity: 'Chromatic' },
  { id: 52, name: 'Janet', image: 'https://cdn.brawlify.com/brawlers/borders/16000057.png', rarity: 'Chromatic' },
  { id: 53, name: 'Otis', image: 'https://cdn.brawlify.com/brawlers/borders/16000059.png', rarity: 'Chromatic' },
  { id: 54, name: 'Sam', image: 'https://cdn.brawlify.com/brawlers/borders/16000060.png', rarity: 'Chromatic' },
  { id: 55, name: 'Gus', image: 'https://cdn.brawlify.com/brawlers/borders/16000061.png', rarity: 'Chromatic' },
  { id: 56, name: 'Buster', image: 'https://cdn.brawlify.com/brawlers/borders/16000062.png', rarity: 'Chromatic' },
  { id: 57, name: 'Bonnie', image: 'https://cdn.brawlify.com/brawlers/borders/16000058.png', rarity: 'Epic' },
  { id: 58, name: 'Mandy', image: 'https://cdn.brawlify.com/brawlers/borders/16000063.png', rarity: 'Chromatic' },
  { id: 59, name: 'Chester', image: 'https://cdn.brawlify.com/brawlers/borders/16000064.png', rarity: 'Chromatic' },
  { id: 60, name: 'Gray', image: 'https://cdn.brawlify.com/brawlers/borders/16000065.png', rarity: 'Chromatic' }
];
