
export interface Brawler {
  id: number;
  name: string;
  image: string;
  rarity: 'Common' | 'Rare' | 'Super Rare' | 'Epic' | 'Mythic' | 'Legendary' | 'Chromatic';
}

export const brawlers: Brawler[] = [
  { id: 1, name: 'Shelly', image: 'https://cdn.brawlify.com/brawler/Shelly.png', rarity: 'Common' },
  { id: 2, name: 'Nita', image: 'https://cdn.brawlify.com/brawler/Nita.png', rarity: 'Common' },
  { id: 3, name: 'Colt', image: 'https://cdn.brawlify.com/brawler/Colt.png', rarity: 'Common' },
  { id: 4, name: 'Bull', image: 'https://cdn.brawlify.com/brawler/Bull.png', rarity: 'Common' },
  { id: 5, name: 'Jessie', image: 'https://cdn.brawlify.com/brawler/Jessie.png', rarity: 'Common' },
  { id: 6, name: 'Brock', image: 'https://cdn.brawlify.com/brawler/Brock.png', rarity: 'Common' },
  { id: 7, name: 'Dynamike', image: 'https://cdn.brawlify.com/brawler/Dynamike.png', rarity: 'Common' },
  { id: 8, name: 'Bo', image: 'https://cdn.brawlify.com/brawler/Bo.png', rarity: 'Common' },
  { id: 9, name: 'Tick', image: 'https://cdn.brawlify.com/brawler/Tick.png', rarity: 'Common' },
  { id: 10, name: 'El Primo', image: 'https://cdn.brawlify.com/brawler/El-Primo.png', rarity: 'Rare' },
  { id: 11, name: 'Barley', image: 'https://cdn.brawlify.com/brawler/Barley.png', rarity: 'Rare' },
  { id: 12, name: 'Poco', image: 'https://cdn.brawlify.com/brawler/Poco.png', rarity: 'Rare' },
  { id: 13, name: 'Rosa', image: 'https://cdn.brawlify.com/brawler/Rosa.png', rarity: 'Rare' },
  { id: 14, name: 'Rico', image: 'https://cdn.brawlify.com/brawler/Rico.png', rarity: 'Super Rare' },
  { id: 15, name: 'Darryl', image: 'https://cdn.brawlify.com/brawler/Darryl.png', rarity: 'Super Rare' },
  { id: 16, name: 'Penny', image: 'https://cdn.brawlify.com/brawler/Penny.png', rarity: 'Super Rare' },
  { id: 17, name: 'Carl', image: 'https://cdn.brawlify.com/brawler/Carl.png', rarity: 'Super Rare' },
  { id: 18, name: 'Jacky', image: 'https://cdn.brawlify.com/brawler/Jacky.png', rarity: 'Super Rare' },
  { id: 19, name: 'Piper', image: 'https://cdn.brawlify.com/brawler/Piper.png', rarity: 'Epic' },
  { id: 20, name: 'Pam', image: 'https://cdn.brawlify.com/brawler/Pam.png', rarity: 'Epic' },
  { id: 21, name: 'Frank', image: 'https://cdn.brawlify.com/brawler/Frank.png', rarity: 'Epic' },
  { id: 22, name: 'Bibi', image: 'https://cdn.brawlify.com/brawler/Bibi.png', rarity: 'Epic' },
  { id: 23, name: 'Bea', image: 'https://cdn.brawlify.com/brawler/Bea.png', rarity: 'Epic' },
  { id: 24, name: 'Nani', image: 'https://cdn.brawlify.com/brawler/Nani.png', rarity: 'Epic' },
  { id: 25, name: 'Edgar', image: 'https://cdn.brawlify.com/brawler/Edgar.png', rarity: 'Epic' },
  { id: 26, name: 'Griff', image: 'https://cdn.brawlify.com/brawler/Griff.png', rarity: 'Epic' },
  { id: 27, name: 'Mortis', image: 'https://cdn.brawlify.com/brawler/Mortis.png', rarity: 'Mythic' },
  { id: 28, name: 'Tara', image: 'https://cdn.brawlify.com/brawler/Tara.png', rarity: 'Mythic' },
  { id: 29, name: 'Gene', image: 'https://cdn.brawlify.com/brawler/Gene.png', rarity: 'Mythic' },
  { id: 30, name: 'Max', image: 'https://cdn.brawlify.com/brawler/Max.png', rarity: 'Mythic' },
  { id: 31, name: 'Mr. P', image: 'https://cdn.brawlify.com/brawler/Mr-P.png', rarity: 'Mythic' },
  { id: 32, name: 'Sprout', image: 'https://cdn.brawlify.com/brawler/Sprout.png', rarity: 'Mythic' },
  { id: 33, name: 'Byron', image: 'https://cdn.brawlify.com/brawler/Byron.png', rarity: 'Mythic' },
  { id: 34, name: 'Squeak', image: 'https://cdn.brawlify.com/brawler/Squeak.png', rarity: 'Mythic' },
  { id: 35, name: 'Spike', image: 'https://cdn.brawlify.com/brawler/Spike.png', rarity: 'Legendary' },
  { id: 36, name: 'Crow', image: 'https://cdn.brawlify.com/brawler/Crow.png', rarity: 'Legendary' },
  { id: 37, name: 'Leon', image: 'https://cdn.brawlify.com/brawler/Leon.png', rarity: 'Legendary' },
  { id: 38, name: 'Sandy', image: 'https://cdn.brawlify.com/brawler/Sandy.png', rarity: 'Legendary' },
  { id: 39, name: 'Amber', image: 'https://cdn.brawlify.com/brawler/Amber.png', rarity: 'Legendary' },
  { id: 40, name: 'Meg', image: 'https://cdn.brawlify.com/brawler/Meg.png', rarity: 'Legendary' },
  { id: 41, name: 'Gale', image: 'https://cdn.brawlify.com/brawler/Gale.png', rarity: 'Chromatic' },
  { id: 42, name: 'Surge', image: 'https://cdn.brawlify.com/brawler/Surge.png', rarity: 'Chromatic' },
  { id: 43, name: 'Colette', image: 'https://cdn.brawlify.com/brawler/Colette.png', rarity: 'Chromatic' },
  { id: 44, name: 'Lou', image: 'https://cdn.brawlify.com/brawler/Lou.png', rarity: 'Chromatic' },
  { id: 45, name: 'Colonel Ruffs', image: 'https://cdn.brawlify.com/brawler/Colonel-Ruffs.png', rarity: 'Chromatic' },
  { id: 46, name: 'Belle', image: 'https://cdn.brawlify.com/brawler/Belle.png', rarity: 'Chromatic' },
  { id: 47, name: 'Buzz', image: 'https://cdn.brawlify.com/brawler/Buzz.png', rarity: 'Chromatic' },
  { id: 48, name: 'Ash', image: 'https://cdn.brawlify.com/brawler/Ash.png', rarity: 'Chromatic' },
  { id: 49, name: 'Lola', image: 'https://cdn.brawlify.com/brawler/Lola.png', rarity: 'Chromatic' },
  { id: 50, name: 'Fang', image: 'https://cdn.brawlify.com/brawler/Fang.png', rarity: 'Chromatic' },
  { id: 51, name: 'Eve', image: 'https://cdn.brawlify.com/brawler/Eve.png', rarity: 'Chromatic' },
  { id: 52, name: 'Janet', image: 'https://cdn.brawlify.com/brawler/Janet.png', rarity: 'Chromatic' },
  { id: 53, name: 'Otis', image: 'https://cdn.brawlify.com/brawler/Otis.png', rarity: 'Chromatic' },
  { id: 54, name: 'Sam', image: 'https://cdn.brawlify.com/brawler/Sam.png', rarity: 'Chromatic' },
  { id: 55, name: 'Gus', image: 'https://cdn.brawlify.com/brawler/Gus.png', rarity: 'Chromatic' },
  { id: 56, name: 'Buster', image: 'https://cdn.brawlify.com/brawler/Buster.png', rarity: 'Chromatic' },
  { id: 57, name: 'Bonnie', image: 'https://cdn.brawlify.com/brawler/Bonnie.png', rarity: 'Epic' },
  { id: 58, name: 'Mandy', image: 'https://cdn.brawlify.com/brawler/Mandy.png', rarity: 'Chromatic' },
  { id: 59, name: 'Chester', image: 'https://cdn.brawlify.com/brawler/Chester.png', rarity: 'Chromatic' },
  { id: 60, name: 'Gray', image: 'https://cdn.brawlify.com/brawler/Gray.png', rarity: 'Chromatic' }
];
